### K-Fold Cross Validation

In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
data = load_breast_cancer(as_frame=True)
df = data.frame
df.head()

In [15]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [16]:
X

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

### Cross validation implementation

In [ ]:
k = 5
kf = KFold(n_splits=k, random_state=None)
model = LogisticRegression(solver='liblinear')

In [ ]:
acc_score = []

In [ ]:
list(kf.split(X))

In [ ]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index, :], X.iloc[test_index, :]
    y_train, y_test = y[train_index], y[test_index]
    
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    
    acc = accuracy_score(predictions, y_test)
    acc_score.append(acc)

In [ ]:
print(acc_score)

In [ ]:
avg_acc_score = sum(acc_score)/k

In [ ]:
print(avg_acc_score)

### cross_val_score()

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
result = cross_val_score(model, X, y, cv=kf)
print(result.mean())